# Example config to show how the tool works
# We will inspect the git dev insights repository here

project_name: git dev insights
repository_url: https://github.com/standan-hulk/git-dev-insights.git
checkout_path: source-repo/data/git-dev-insights
analyse_result_path: source-repo/generated-stats/git-dev-insights