# Example config to show how the tool works
# We will inspect the phpmyadmin repository here

project_name: PhpMyAdmin
repository_url: https://github.com/phpmyadmin/phpmyadmin.git
checkout_path: source-repo/data/phpmyadmin
analyse_result_path: source-repo/generated-stats/phpmyadmin