# Example config to show how the tool works
# We will inspect the contao repository here

project:
  project_name: Contao
  repository_url: https://github.com/contao/contao.git
  checkout_path: insights/checkout/contao
  analyse_result_path: insights/generated/contao

stats:
  time_range_weeks: 150