PHP:
  - php
  - php3
  - php4
  - php5
  - php7

SQL:
  - sql

Less:
  - less

Sass:
  - scss

CSS:
  - css

HTML:
  - html
  - htm
  - phtml

JavaScript [JS FILES]:
  - js

TypeScript:
  - ts

YAML:
  - yaml
  - yml

XML:
  - xml

Documentation:
  - rst
  - md

# deep insights
JavaScript [INLINE]:
  - __inline_js__

JQuery [INLINE]:
  - __inline_jquery__

JQuery [FILES]:
  - __file_jquery__