# Example config to show how the tool works
# We will inspect the phpmyadmin repository here

project:
  project_name: PhpMyAdmin
  repository_url: https://github.com/phpmyadmin/phpmyadmin.git
  checkout_path: insights/checkout/phpmyadmin
  analyse_result_path: insights/generated/phpmyadmin

stats:
  time_range_weeks: 150