# Example config to show how the tool works
# We will inspect the redaxo repository here

project:
  project_name: Redaxo
  repository_url: https://github.com/redaxo/redaxo.git
  checkout_path: insights/checkout/redaxo
  analyse_result_path: insights/generated/redaxo