# Example config to show how the tool works
# We will inspect the redaxo repository here

project_name: Redaxo
repository_url: https://github.com/redaxo/redaxo.git
checkout_path: source-repo/data/redaxo
analyse_result_path: source-repo/generated-stats/redaxo